config/routes.rb
Webapp::Application.routes.draw do
  
  resources :user_views

  post '/rate' => 'rater#create', :as => 'rate'
   resources :profiles

  devise_for :users 
   
  
  resources :companies
   
  
  get "companies/index"
  
  root 'companies#index'
  resources :company_ratings do
    collection do
      get 'user_rating'
    end
  end

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :company_profiles
  has_many :companies, :through => :company_profiles

  accepts_nested_attributes_for :company_profiles, :allow_destroy => true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = current_user.build_profile
    @profile.company_profiles.build
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.create_profile!(profile_params)
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit!
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= nested_form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.fields_for :company_profiles do |task_form| %>
    <div class="field">
      <%= task_form.label :company_id %><br />
      <%= task_form.collection_select :company_id, Company.all, :id, :name %>
    </div>
    <div class="field">
      <%= task_form.label :to_date %><br />
      <%= task_form.text_field :to_date,:class=>"to_date" %>
    </div>
    <div class="field">
      <%= task_form.label :from_date %><br />
      <%= task_form.text_field :from_date,:class=>"from_date"  %>
    </div>
    <div class="field">
      <%= task_form.link_to_remove "Remove this company" %>
    </div>
  <% end %>
<p><%= f.link_to_add "Add a company", :company_profiles %></p>

   <%#= f.input :company_ids ,:collection =>Company.all, :as => :check_boxes %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%#= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.company %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%#= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Companies</strong>
  <% @profile.companies.each do |company| %>
  	<li><%= company.name %></li>
  <% end %>
</p>

<p>
  <strong>User:</strong>
  <%= @profile.user.email %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%#= link_to 'Back', profiles_path %>