config/routes.rb
Webapp::Application.routes.draw do
  
  resources :user_views

  post '/rate' => 'rater#create', :as => 'rate'
   resources :profiles

  devise_for :users 
   
  
  resources :companies
   
  
  get "companies/index"
  
  root 'companies#index'
  resources :company_ratings do
    collection do
      get 'user_rating'
    end
  end

end

app/controllers/user_views_controller.rb
class UserViewsController < ApplicationController
  before_action :set_user_view, only: [:show, :edit, :update, :destroy]

  # GET /user_views
  # GET /user_views.json
  def index
    #@user_views = UserView.all
  end

  # GET /user_views/1
  # GET /user_views/1.json
  def show
  end

  # GET /user_views/new
  def new
    @user_view = UserView.new
  end

  # GET /user_views/1/edit
  def edit
  end

  # POST /user_views
  # POST /user_views.json
  def create
    @user_view = UserView.new(user_view_params)

    respond_to do |format|
      if @user_view.save
        format.html { redirect_to @user_view, notice: 'User view was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_view }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_views/1
  # PATCH/PUT /user_views/1.json
  def update
    respond_to do |format|
      if @user_view.update(user_view_params)
        format.html { redirect_to @user_view, notice: 'User view was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_view.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_views/1
  # DELETE /user_views/1.json
  def destroy
    @user_view.destroy
    respond_to do |format|
      format.html { redirect_to user_views_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_view
      @user_view = UserView.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_view_params
      params.require(:user_view).permit(:company_id, :user_id)
    end
end

app/helpers/user_views_helper.rb
module UserViewsHelper
end

app/views/user_views/_form.html.erb
<%= semantic_form_for @user_view do |f| %>
  <%= f.inputs do %>
    <%= f.input :company_id %>
    <%= f.input :user_id %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/user_views/edit.html.erb
<h1>Editing user_view</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_view %> |
<%= link_to 'Back', user_views_path %>

app/views/user_views/index.html.erb
<h1>Listing user_views</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_views.each do |user_view| %>
      <tr>
        <td><%= user_view.company_id %></td>
        <td><%= user_view.user_id %></td>
        <td><%= link_to 'Show', user_view %></td>
        <td><%= link_to 'Edit', edit_user_view_path(user_view) %></td>
        <td><%= link_to 'Destroy', user_view, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User view', new_user_view_path %>

app/views/user_views/new.html.erb
<h1>New user_view</h1>

<%= render 'form' %>

<%= link_to 'Back', user_views_path %>

app/views/user_views/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company:</strong>
  <%= @user_view.company_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_view.user_id %>
</p>

<%= link_to 'Edit', edit_user_view_path(@user_view) %> |
<%= link_to 'Back', user_views_path %>