config/routes.rb
Webapp::Application.routes.draw do
  
  resources :user_views

  post '/rate' => 'rater#create', :as => 'rate'
   resources :profiles

  devise_for :users 
   
  
  resources :companies
   
  
  get "companies/index"
  
  root 'companies#index'
  resources :company_ratings do
    collection do
      get 'user_rating'
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
	#has_many :ratings, :through=> :users
    #has_many :ratings
    has_many :company_ratings, :through=> :users
    has_many :company_ratings
	has_many :company_profiles
  has_many :profiles, :through => :company_profiles
  accepts_nested_attributes_for :company_profiles, :allow_destroy => true
  
  has_attached_file :logo, :styles => { :medium => "100x100>", :original=> "50x50", :thumb => "100x100>" },
   :default_url => "/images/:style/missing.png"

  def update_attribscore
    #to find attrib1
     #rating_size=company_ratings.collect(&:satisfaction).compact.size
     
     if company_ratings.collect(&:satisfaction).compact.empty?
      attrb1 = nil
       rating_size=nil
      else
        rating_size=company_ratings.collect(&:satisfaction).compact.count
     attrb1= (company_ratings.collect(&:satisfaction).compact.sum.to_f/rating_size) 
     end
     update_attributes(:attrib_satisfaction => attrb1)

    #to find attrib2
    
     if company_ratings.collect(&:work_environment).compact.empty?
         attrb2 = nil
          rating_size1=nil
      else
         rating_size1=company_ratings.collect(&:work_environment).compact.count
         attrb2= (company_ratings.collect(&:work_environment).compact.sum.to_f/rating_size1 )
     end
     update_attributes(:attrib_work_environment => attrb2)
     
     #to find attrib3
     #rating_size2=company_ratings.collect(&:cd).compact.count
     if company_ratings.collect(&:cd).compact.empty?
      attrb3 = nil
      rating_size2=nil
    else
      rating_size2=company_ratings.collect(&:cd).compact.count
     attrb3= (company_ratings.collect(&:cd).compact.sum.to_f/rating_size2 )
   end

     update_attributes(:attrib_cd => attrb3)

     #To find attrib4

     
      if company_ratings.collect(&:flexibility).compact.empty?
         attrb4 = nil
         rating_size3=nil

      else
        rating_size3=company_ratings.collect(&:flexibility).compact.count
         attrb4 = (company_ratings.collect(&:flexibility).compact.sum.to_f/rating_size3 )
      end
     #attrb4 = (company_ratings.collect { |x| x.flexibility.to_i}.sum.to_f/rating_size3 )
     update_attributes(:attrib_flexibility => attrb4)
      

      #To find attrib5
     
     if company_ratings.collect(&:relation).compact.empty?
         attrb5 = nil
         rating_size4=nil
      else
        rating_size4=company_ratings.collect(&:relation).compact.count
        attrb5=(company_ratings.collect(&:relation).compact.sum.to_f/rating_size4 )
     end
     update_attributes(:attrib_relation => attrb5)


     #To find attrib6

     #rating_size5=company_ratings.collect(&:leadership).compact.count
     if company_ratings.collect(&:leadership).compact.empty?
         attrb6 = nil
         rating_size5=nil
      else
        rating_size5=company_ratings.collect(&:leadership).compact.count
         attrb6=(company_ratings.collect(&:leadership).compact.sum.to_f/rating_size5 ) 
     end
     update_attributes(:attrib_leadership => attrb6 )

     #To find attrib7

     
     if company_ratings.collect(&:pride).compact.empty?
         attrb7=nil
         rating_size6=nil
     else
      rating_size6=company_ratings.collect(&:pride).compact.count
       attrb7= (company_ratings.collect(&:pride).compact.sum.to_f/rating_size6 )
     end
     update_attributes(:attrib_pride => attrb7)

     #To find attrib8

     #rating_size7=company_ratings.collect(&:opportunities).compact.count

     if company_ratings.collect(&:opportunities).compact.empty?
        attrb8=nil
        rating_size7=nil
     else
        rating_size7=company_ratings.collect(&:opportunities).compact.count
        attrb8=(  company_ratings.collect(&:opportunities).compact.sum.to_f/rating_size7 )
     end
     update_attributes(:attrib_opportunities =>attrb8  )


     #To find attrib9

     
     
     if company_ratings.collect(&:opinion).compact.empty?
        attrb9=nil
        rating_size8=nil
      else
        rating_size8=company_ratings.collect(&:opinion).compact.count
         attrb9=(company_ratings.collect(&:opinion).compact.sum.to_f/rating_size8 )
      end
     update_attributes(:attrib_opinion => attrb9)


     #To find attrib10
     
    if company_ratings.collect(&:stimulatingjob).compact.empty?
      attrb10=nil
      rating_size9=nil
    else
      rating_size9=company_ratings.collect(&:stimulatingjob).compact.count
     attrb10=(company_ratings.collect(&:stimulatingjob).compact.sum.to_f/rating_size9 )
    end
     update_attributes(:attrib_stimulatingjob => attrb10 )

     #To find attrib11

     
     if company_ratings.collect(&:innovation).compact.empty?
      attrb11=nil
      rating_size10=nil
    else
      rating_size10=company_ratings.collect(&:innovation).compact.count
     attrb11=(company_ratings.collect(&:innovation).compact.sum.to_f/rating_size10 )
    end
     update_attributes(:attrib_innovation => attrb11 )


     #To find attrib12

     

     if company_ratings.collect(&:management).compact.empty?
      attrb12=nil
      rating_size11=nil
    else
      rating_size11=company_ratings.collect(&:management).compact.count
         attrb12=(company_ratings.collect(&:management).compact.sum.to_f/rating_size11 )
    end
     update_attributes(:attrib_management => attrb12)
     

     #To find attrib13


     

     if company_ratings.collect(&:compensation).compact.empty?
      attrb13=nil
      rating_size12=nil
    else
      rating_size12=company_ratings.collect(&:compensation).compact.count
     attrb13=(company_ratings.collect(&:compensation).compact.sum.to_f/rating_size12 )
    end
     update_attributes(:attrib_compensation => attrb13)

     
     #To find attrib14
     
     if company_ratings.collect(&:workload).compact.empty?
      attrb14=nil
      rating_size13=nil
    else
      rating_size13=company_ratings.collect(&:workload).compact.count
     attrb14=(company_ratings.collect(&:workload).compact.sum.to_f/rating_size13 )
    end
     update_attributes(:attrib_workload=> attrb14)


     #To find attrib15

     
     if company_ratings.collect(&:equality).compact.empty?
      attrb15=nil
      rating_size14=nil
    else
      rating_size14=company_ratings.collect(&:equality).compact.count
     attrb15=(company_ratings.collect(&:equality).compact.sum.to_f/rating_size14 )
    end
     update_attributes(:attrib_equality => attrb15)

     #To find attrib16

     
     if company_ratings.collect(&:objectives).compact.empty?
      attrb16=nil
      rating_size15=nil
    else
      rating_size15=company_ratings.collect(&:objectives).compact.count
      attrb16=(company_ratings.collect(&:objectives).compact.sum.to_f/rating_size15 )
    end
     update_attributes(:attrib_objectives => attrb16)

     #To find attrib17

     
     if company_ratings.collect(&:cooperation).compact.empty?
      attrb17 = nil
      rating_size16=nil
    else
      rating_size16=company_ratings.collect(&:cooperation).compact.count
     attrb17=(company_ratings.collect(&:cooperation).compact.sum.to_f/rating_size16 )
    end
     update_attributes(:attrib_cooperation => attrb17 )


     #To find attrib18


     

     if company_ratings.collect(&:guidance).compact.empty?
      attrb18= nil
      rating_size17=nil
    else
      rating_size17=company_ratings.collect(&:guidance).compact.count
      attrb18=(company_ratings.collect(&:guidance).compact.sum.to_f/rating_size17 )
    end
     update_attributes(:attrib_guidance => attrb18)
     #update_attributes(:attrib_guidance => (  company_ratings.collect(&:guidance).compact.sum.to_f/rating_size17)
     #company_ratings.sum("guidance").to_f
     

     #To find attrib19
     

     if company_ratings.collect(&:reward).compact.empty?
      attrib19=nil
      rating_size18=nil
    else
      rating_size18=company_ratings.collect(&:reward).compact.count
     attrb19=(company_ratings.collect(&:reward).compact.sum.to_f/rating_size18 )
   end
     update_attributes(:attrib_reward =>  attrb19)

     #To find attrib20
     
     if company_ratings.collect(&:career).compact.empty?
      attrb20=nil
      rating_size19=nil
    else
      rating_size19=company_ratings.collect(&:career).compact.count
     attrb20=(company_ratings.collect(&:career).compact.sum.to_f/rating_size19 )
    end
     update_attributes(:attrib_career => attrb20 )

     #To find attrib21
     
     #rating_size20=company_ratings.collect(&:transparancy).compact.count
     if company_ratings.collect(&:transparancy).compact.empty?
       attrb21=nil
       rating_size20 = nil
     else
       rating_size20=company_ratings.collect(&:transparancy).compact.count
       attrb21= (  company_ratings.collect(&:transparancy).compact.sum.to_f/rating_size20  )
      end
     update_attributes(:attrib_transparancy=> attrb21 )
     

     #raise attrb1.inspect 
     #not sum count 

     counting= [rating_size,rating_size1,rating_size2,rating_size3,rating_size4,rating_size5,rating_size6,rating_size7,rating_size8,rating_size9,rating_size10,rating_size11,rating_size12,rating_size13,rating_size14,rating_size15,rating_size16,rating_size17,rating_size18,rating_size19,rating_size20]
     review = counting.compact.count
     #raise review.inspect
     #review= rating_size+rating_size1+rating_size2+rating_size3+rating_size4+rating_size5+rating_size6+rating_size7+rating_size8+rating_size9+rating_size10+rating_size11+rating_size12+rating_size13+rating_size14+rating_size15+rating_size16+rating_size17+rating_size18+rating_size19+rating_size20
     update_attributes(:reviews =>   review)
     
     totalreview = company_ratings.count
     update_attributes(:totalreviews => totalreview)
    #raise rating_size1.inspect
      update_satisfaction
      update_rank

  end

  #after_update :update_satisfaction
  
 
  def update_satisfaction
     review= self.reviews
     #raise review.inspect

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user! , :only => [:show]
  #, :except => [:index] 
  
  

  def index
    @companies = Company.all.order('rank DESC NULLS LAST')
    #@companies = CompanyRating.select('company_id,avg(satisfaction+work_environment+cd+flexibility+relation+leadership+pride+opportunities+opinion+stimulatingjob+innovation+management+compensation+workload+equality+objectives+cooperation+guidance+reward+career+transparancy) as rating, COUNT(DISTINCT(user_id,company_id)) as rank').group('company_id').order("rank DESC, rating ASC") 
    #count = CompanyRating.count      
    #@companies = CompanyRating.select('company_id,avg(satisfaction+work_environment+cd+flexibility+relation+leadership+pride+opportunities+opinion+stimulatingjob+innovation+management+compensation+workload+equality+objectives+cooperation+guidance+reward+career+transparancy) as rating, COUNT(DISTINCT(user_id,company_id)) as rank').group('company_id').order("coalesce('rank', #{count}) ASC")
    #@companies=CompanyRating.select('avg(satisfaction+work_environment+cd+flexibility+relation+leadership+pride+opportunities+opinion+stimulatingjob+innovation+management+compensation+workload+equality+objectives+cooperation+guidance+reward+career+transparancy) as rating,COUNT(DISTINCT(user_id,company_id)) as rank').order('rank')
  end

 
  def show
    @company = Company.find(params[:id])
    #@article.user_id = current_user.id 
    company_rating = CompanyRating.where( :company_id =>@company.id,
                                          :user_id => current_user.id ) 
    #rating_size = company_rating.size

    
    @avg_satisfaction = company_rating.collect(&:satisfaction)
    @avg_work_environment = company_rating.collect(&:work_environment)
    @avg_cd = company_rating.collect(&:cd)
    @avg_flexibility = company_rating.collect(&:flexibility)
    @avg_relation = company_rating.collect(&:relation)

    @avg_leadership = company_rating.collect(&:leadership)

     rating_size6=company_rating.collect(&:pride).count
    @avg_pride = (company_rating.collect(&:pride))
    @avg_opportunities = company_rating.collect(&:opportunities)
    @avg_opinion = company_rating.collect(&:opinion)
    @avg_stimulatingjob = company_rating.collect(&:stimulatingjob)
    #@avg_stimulatingjob = (company_rating.collect(&:stimulatingjob).compact.sum.to_i/rating_size if company_rating.blank?)
    @avg_innovation = company_rating.collect(&:innovation)
    @avg_management= company_rating.collect(&:management)
    @avg_compensation = company_rating.collect(&:compensation)
    @avg_workload = company_rating.collect(&:workload)
    @avg_equality = company_rating.collect(&:equality)
    @avg_objectives= company_rating.collect(&:objectives)
    @avg_cooperation = company_rating.collect(&:cooperation)
    @avg_guidance = company_rating.collect(&:guidance)
    @avg_reward = company_rating.collect(&:reward)
    @avg_career = company_rating.collect(&:career)
    @avg_transparancy = company_rating.collect(&:transparancy)
    
    #arr= [avg_satisfaction,@avg_work_environment,@avg_cd,@avg_flexibility,@avg_relation,@avg_leadership,@avg_pride,@avg_opportunities,@avg_opinion,@avg_stimulatingjob,@avg_innovation,@avg_management,@avg_compensation,@avg_workload,@avg_equality,@avg_objectives,@avg_cooperation,@avg_guidance,@avg_reward,@avg_career,@avg_transparancy]
    #@current_user_satisfaction = @avg_satisfaction+@avg_work_environment+@avg_cd+@avg_flexibility+@avg_relation+@avg_leadership+@avg_pride+@avg_opportunities+@avg_opinion+@avg_stimulatingjob+@avg_innovation+@avg_management+@avg_compensation+@avg_workload+@avg_equality+@avg_objectives+@avg_cooperation+@avg_guidance+@avg_reward+@avg_career+@avg_transparancy).compact/21
    arr= @avg_satisfaction+@avg_work_environment+@avg_cd+@avg_flexibility+@avg_relation+@avg_leadership+@avg_pride+@avg_opportunities+@avg_opinion+@avg_stimulatingjob+@avg_innovation+@avg_management+@avg_compensation+@avg_workload+@avg_equality+@avg_objectives+@avg_cooperation+@avg_guidance+@avg_reward+@avg_career+@avg_transparancy
     @current_user_satisfaction = arr.flatten.compact.sum / arr.flatten.compact.size if arr.flatten.compact.present?
     #size = arr.compact.size
    #total= avg_satisfaction+avg_work_environment+avg_cd+avg_flexibility+avg_relation+avg_leadership+avg_pride+avg_opportunities+avg_opinion+avg_stimulatingjob+avg_innovation+avg_management+avg_compensation+avg_workload+avg_equality+avg_objectives+avg_cooperation+avg_guidance+avg_reward+avg_career+avg_transparancy
   #raise size.inspect 
   #@total= (@avg_satisfaction+@avg_work_environment+@avg_cd+@avg_flexibility+@avg_relation+@avg_leadership+@avg_pride+@avg_opportunities+@avg_opinion+@avg_stimulatingjob+@avg_innovation+@avg_management+@avg_compensation+@avg_workload+@avg_equality+@avg_objectives+@avg_cooperation+@avg_guidance+@avg_reward+@avg_career+@avg_transparancy).compact/21
  #arr= @avg_satisfaction+@avg_work_environment+@avg_cd+@avg_flexibility+@avg_relation+@avg_leadership+@avg_pride+@avg_opportunities+@avg_opinion+@avg_stimulatingjob+@avg_innovation+@avg_management+@avg_compensation+@avg_workload+@avg_equality+@avg_objectives+@avg_cooperation+@avg_guidance+@avg_reward+@avg_career+@avg_transparancy
   #(company.attrib_satisfaction+company.attrib_work_environment+company.attrib_cd+company.attrib_flexibility+company.attrib_relation+company.attrib_leadership+company.attrib_pride+company.attrib_opportunities+company.attrib_opinion+company.attrib_stimulatingjob+company.attrib_innovation+company.attrib_management+company.attrib_compensation+company.attrib_workload+company.attrib_equality+company.attrib_objectives+company.attrib_cooperation+company.attrib_guidance+company.attrib_reward+company.attrib_career+company.attrib_transparancy)/company.reviews 

    #@total = arr.inject{ |sum, el| sum + el }.to_i / arr.size
  end

 

 
  def new
    @company = Company.new
end

  def create
    @company = Company.new(comp_params)
    if @company.save
      
      flash[:success] = "Welcome to skillable"
      redirect_to root_url
    else
      render 'new'
    end
  end
  

  private

  def comp_params
    params.require(:company).permit(:name, :place, :Description,:logo)
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this companies from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :place %><br />
    <%= f.text_field :place %>
  </div>
  <div class="field">
    <%= f.label :Description %><br />
    <%= f.text_field :Description %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.file_field :logo %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/index.html.erb
<h1>Companies List</h1>

<table id="company" border="3" layout= "fixed" width=" 100%"  >
  <colgroup>
    <col style="width: 33%" />
    <col style="width: 33%" />
    <col style="width: 33%" />
  
  <tr>
    <th>Rank</th>
    <th>Name</th>
    <th>Logo</th>
    <th>Place</th>
    <th> Total Satisfaction score</th>
    <th> Total no.of Reviews</th>

   
    <th></th>
  </tr>
  
<% @companies.each do |company| %>  
  <tr >
    <td><%= company.rank.to_i%></td>
    <td><%= company.name %></td>
    <td><%=image_tag company.logo.url(:thumb)%></td>
    <td><%= company.place %></td>
    <td><%= company.satisfaction.to_i %> </td>
    <td><%= company.totalreviews.to_i %></td>
    <td><%= link_to 'VIEW', company %></td>
    

<% end %>
         

  </tr>

 </colgroup>
</table>

<br />

<%= link_to 'ADD New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 <h1> <b>Title:</b>
  <%= @company.name %>
</p></h1>
<p>
  <b>Logo:</b><br>
  <%=image_tag @company.logo.url(:thumb)%>
</p>
<p>
 <h2> <b>Place:</b></h2>
 <h2> <%= @company.place %></h2>
</p>

<body>
  <b>Description:</b>
 <h3> <%= @company.Description %></h3>

<b>Total:</b>
  <h3>Satisfaction Score:- <%= @company.satisfaction%><br/></h3>
  <h3> <b>No.of Reviews:- </b><%= @company.totalreviews.to_i %><br/></h3>
  <h3>Current User Satisfaction:- <%= @current_user_satisfaction %> <br/></h3>


<h2><b>Rating:</b></h2>
<table id="company" border="3" layout= "fixed" width=" 100%"  >
  <colgroup>
    <col style="width: 33%" />
    <col style="width: 33%" />
    <col style="width: 33%" />

  <tr>
    <th> </th>
    <th>Trust and Responsibility Given:- </th>
    <th>Work, Amenities & Gadgets:-</th>
    <th>Sex,Age & Cultural Diversity:- </th>
    <th>Autonomy & Flexibility:- </th>
    <th> Atmosphere, Mood & Relationship with Team:- </th>
    <th> Trust on Management & Leadership:-</th>
    <th>Sense of Belonging & pride for the company:-  </th>
    <th> Learning & Improvement opportunities:- </th>
    <th>Opportunity to voice own Opinion:- </th>
    <th>Stimulating Job:- </th>
    <th>Creativity & Innovation Opportunities:- </th>
    <th>RelationShip with Supervisor /Management:- </th>
    <th>Compensation & Benefits:- </th>
    <th>Workload Balance:- </th>
    <th>Equality & Fairness:-</th>
    <th>Clarity of Role, Goals & Objectives:- </th>
    <th>Cooperation, Coordination, Collabration & Efficiency:- </th>

    <th>Guidance & Feedback received:- </th>
    <th>Recognition & Reward:- </th>
    <th>Career Growth Opportunities:- </th>
    <th>Consistency & Transperency :- </th>
  </tr>
  <tr >
  <th scope="row"> <%= current_user.email %></th>
   <td><%= @avg_satisfaction.shift %></td>
    <td><%= @avg_work_environment .shift %></td>
    <td><%= @avg_cd.shift   %></td>
    <td><%= @avg_flexibility.shift  %></td>
    <td><%=@avg_relation.shift  %></td>
    <td> <%=  @avg_leadership.shift   %></td>
    <td> <%= @avg_pride.shift  %></td>
    <td> <%=  @avg_opportunities.shift  %></td>
    <td> <%= @avg_opinion.shift %></td>
    <td> <%=  @avg_stimulatingjob.shift  %></td>
    <td> <%= @avg_innovation.shift %></td>
    <td> <%=  @avg_management.shift  %></td>
    <td> <%= @avg_compensation.shift  %></td>
    <td> <%=  @avg_workload.shift  %></td>
    <td> <%= @avg_equality.shift  %></td>
    <td> <%= @avg_objectives.shift %></td>
    <td><%= @avg_cooperation.shift  %></td>

    <td><%=  @avg_guidance.shift  %></td>
    <td><%= @avg_reward.shift  %></td>
    <td><%= @avg_career.shift  %></td>
    <td><%= @avg_transparancy.shift  %></td>
        
  </tr>

  <tr >
  <th scope="row">Total AVG:</th>
   <td><%= @company.attrib_satisfaction %></td>
    <td><%= @company.attrib_work_environment  %></td>
    <td><%= @company.attrib_cd  %></td>
    <td><%= @company.attrib_flexibility  %></td>
    <td><%=@company.attrib_relation  %></td>
    <td> <%=  @company.attrib_leadership   %></td>
    <td> <%= @company.attrib_pride  %></td>
    <td> <%=  @company.attrib_opportunities  %></td>
    <td> <%= @company.attrib_opinion %></td>
    <td> <%=  @company.attrib_stimulatingjob  %></td>
    <td> <%= @company.attrib_innovation %></td>
    <td> <%=  @company.attrib_management  %></td>
    <td> <%= @company.attrib_compensation  %></td>
    <td> <%=  @company.attrib_workload  %></td>
    <td> <%= @company.attrib_equality  %></td>
    <td> <%= @company.attrib_objectives %></td>
    <td><%= @company.attrib_cooperation  %></td>

    <td><%=  @company.attrib_guidance  %></td>
    <td><%= @company.attrib_reward  %></td>
    <td><%= @company.attrib_career  %></td>
    <td><%= @company.attrib_transparancy  %></td>
        
  </tr>
      
 </colgroup>
</table>
  


 


<br /><br />

 |
<%= link_to 'Back', companies_path %>
</body>