config/routes.rb
Webapp::Application.routes.draw do
  
  resources :user_views

  post '/rate' => 'rater#create', :as => 'rate'
   resources :profiles

  devise_for :users 
   
  
  resources :companies
   
  
  get "companies/index"
  
  root 'companies#index'
  resources :company_ratings do
    collection do
      get 'user_rating'
    end
  end

end

app/models/company_rating.rb
class CompanyRating < ActiveRecord::Base
  belongs_to :user
  belongs_to :company
  has_one :companies, :through=>:users
  after_create :update_post_update_attribscore
  #def update_avgratings
  #company_rating = CompanyRating.where(:company_id =>user.company.id)
  #rating_size = ratings.collect(&:satisfaction).count
  #rating_size = collect(&:satisfaction).count
  #update_attributes(:avg_satisfaction => collect(&:satisfaction).sum.to_f/rating_size)
 #update_attributes(:avg_satisfaction => self.SUM(:satisfaction) / (:satisfaction).count)
  #update_attributes(:avg_satisfaction => self.SUM(:satisfaction)/COUNT(:satisfaction))
#end

  def update_post_update_attribscore
   self.company.update_attribscore
  end

  
end
 

app/controllers/company_ratings_controller.rb
class CompanyRatingsController < ApplicationController
  before_action :set_company_rating, only: [:show, :edit, :update, :destroy]
 
  # GET /company_ratings
  # GET /company_ratings.json
  def index
    @company_ratings = CompanyRating.all
  end

  # GET /company_ratings/1
  # GET /company_ratings/1.json
  def show
  end

  # GET /company_ratings/new
  def new
    @company_rating = CompanyRating.new

  end

  # GET /company_ratings/1/edit
  def edit
  end

  # POST /company_ratings
  # POST /company_ratings.json
  def create
    # debugger
    @company_rating = current_user.company_ratings.new(company_rating_params)

    # respond_to do |format|
      if @company_rating.save
        flash[:notice] = 'Company rating was successfully created.'
        redirect_to company_path(session[:company_id])
        # format.html { redirect_to @company_rating, notice: 'Company rating was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @company_rating }
      else
        render action: 'new' ,:layout => false
        # format.html { render action: 'new' }
        # format.json { render json: @company_rating.errors, status: :unprocessable_entity }
      end
    # end
  end




  # PATCH/PUT /company_ratings/1
  # PATCH/PUT /company_ratings/1.json
  def update
    respond_to do |format|
      if @company_rating.update(company_rating_params)
        format.html { redirect_to @company_rating, notice: 'Company rating was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @company_rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_ratings/1
  # DELETE /company_ratings/1.json
  def destroy
    @company_rating.destroy
    respond_to do |format|
      format.html { redirect_to company_ratings_url }
      format.json { head :no_content }
    end
  end
=begin
  def user_rating   
    company_id = current_user.profile.companies.map(&:id) 
    #rating = current_user.company_ratings.find(:all,:conditions=>["user_id = ? and company_id IN (?)",current_user.id,company_id])
    rating = current_user.company_ratings.where("user_id = ? and company_id IN (?)",current_user.id,company_id)
    if rating.size !=company_id.size
      if session[:company_id].blank?
        session[:company_id] = params[:company_id] 
        render :json=>"redirect".to_json
      else
        company_id = company_id - rating.map(&:company_id)
        @company_rating = current_user.company_ratings.new(:company_id=>company_id.first)
        @company = Company.find(company_id.first)
        session[:company_id] = params[:company_id]
        render :layout =>false
      end
    else
      session[:company_id] = nil
      render :json => "redirect".to_json
      # redirect_to company_path(params[:company_id])
    end
    end
=end
def user_rating  
  if current_user.profile.nil?
    #new_profile_path  
     render :json => "redirect".to_json  
  else
   company_id = current_user.profile.companies.map(&:id)
   #rating = current_user.company_ratings.find(:all,:conditions=>["user_id = ? and company_id IN (?)",current_user.id,company_id])
   rating = current_user.company_ratings.where("user_id = ? and company_id IN (?)",current_user.id,company_id)
   view =  UserView.find_by_user_id(current_user.id)
   #views = current_user.user_view
   size =  rating.size !=company_id.size
   #raise size.inspect
   if rating.size !=company_id.size
     if view.blank? 
      companyid= params[:company_id]
      view =   UserView.create(:user_id=>current_user.id)
     #if session[:company_id].blank? 
        #User_view.update_attributes(:user_id => current_user_id)
        #session[:company_id] = params[:company_id]
       render :json=>"redirect".to_json
      
     else
       company_id = company_id - rating.map(&:company_id)
       @company_rating = current_user.company_ratings.new(:company_id=>company_id.first)
       @company = Company.find(company_id.first)
       session[:company_id] = params[:company_id]
       render :layout =>false
     
       
     end
   else
     #session[:company_id] = nil
     #view =   UserView.destroy(:user_id=>current_user.id)
     render :json => "redirect".to_json
     # redirect_to company_path(params[:company_id])
   end
 end
 end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_rating
      @company_rating = CompanyRating.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_rating_params
      params.require(:company_rating).permit(:user_id, :company_id, :satisfaction, :work_environment, :cd, :flexibility, :relation,  :leadership, :pride,  :opportunities,  :opinion,  :stimulatingjob,  :innovation,  :management,  :compensation,  :workload,  :equality,  :objectives,  :cooperation,  :guidance,  :reward,  :career,  :transparancy)
    end


  def set_user_view
      @user_view = UserView.find(params[:id])
    end

end

app/helpers/company_ratings_helper.rb
module CompanyRatingsHelper
end

app/views/company_ratings/_form.html.erb
<%= simple_form_for(@company_rating) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.association :user %>
    <%= f.association :company %>
    <%= f.input :rating %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/company_ratings/edit.html.erb
<h1>Editing company_rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @company_rating %> |
<%= link_to 'Back', company_ratings_path %>

app/views/company_ratings/index.html.erb
<h1>Listing company_ratings</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Company</th>
      <th>Rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @company_ratings.each do |company_rating| %>
      <tr>
        <td><%= company_rating.user %></td>
        <td><%= company_rating.company %></td>
        <td><%= company_rating.rating %></td>
        <td><%= link_to 'Show', company_rating %></td>
        <td><%= link_to 'Edit', edit_company_rating_path(company_rating) %></td>
        <td><%= link_to 'Destroy', company_rating, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company rating', new_company_rating_path %>

app/views/company_ratings/new.html.erb
<h1>New company_rating</h1>

<%= render 'form' %>

<%= link_to 'Back', company_ratings_path %>

app/views/company_ratings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @company_rating.user %>
</p>

<p>
  <strong>Company:</strong>
  <%= @company_rating.company %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @company_rating.rating %>
</p>

<%= link_to 'Edit', edit_company_rating_path(@company_rating) %> |
<%= link_to 'Back', company_ratings_path %>

app/views/company_ratings/user_rating.html.erb
<h1><%=@company.name%> Rating</h1>
<%= semantic_form_for(@company_rating) do |f| %>


  <div class="form-inputs">
    <%= hidden_field_tag 'company_rating[company_id]' ,@company_rating.company_id %>
    <%= f.input :satisfaction, as: :slider,  step: 1, color: 'red'%>
    <%= f.input :work_environment,as: :slider, step: 1, color: 'red' %>
    <%= f.input :cd, as: :slider, step: 1, color: 'red'%>
    <%= f.input :flexibility,as: :slider, step: 1, color: 'red' %>
    <%= f.input :relation, as: :slider, step: 1, color: 'red'%>
    <%= f.input :leadership,as: :slider, step: 1, color: 'red' %>
    <%= f.input :pride,as: :slider, step: 1, color: 'red' %>
    <%= f.input :opportunities, as: :slider, step: 1, color: 'red'%>
    <%= f.input :opinion,as: :slider, step: 1, color: 'red' %>
    <%= f.input :stimulatingjob, as: :slider, step: 1, color: 'red'%>
    <%= f.input :innovation,as: :slider, step: 1, color: 'red' %>
    <%= f.input :management, as: :slider, step: 1, color: 'red'%>
    <%= f.input :compensation,as: :slider, step: 1, color: 'red' %>
    <%= f.input :workload, as: :slider, step: 1, color: 'red'%>
    <%= f.input :equality,as: :slider, step: 1, color: 'red' %>
    <%= f.input :objectives,as: :slider, step: 1, color: 'red' %>
    <%= f.input :cooperation,as: :slider, step: 1, color: 'red' %>
    <%= f.input :guidance, as: :slider, step: 1, color: 'red'%>
    <%= f.input :reward,as: :slider, step: 1, color: 'red' %>
    <%= f.input :career, as: :slider, step: 1, color: 'red'%>
    <%= f.input :transparancy,as: :slider, step: 1, color: 'red' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

	 